name: mynotes
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.10+16

environment:
  sdk: ">=3.0.0 <4.0.0"  # Updated SDK constraint to 3.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.6
  firebase_analytics: ^11.3.5
  firebase_messaging: ^15.1.5
  firebase_remote_config: ^5.1.5

  # Other dependencies remain unchanged
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  sqflite: ^2.0.1
  path_provider: ^2.0.8
  path: ^1.8.0
  
  share_plus: ^7.2.1
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  intl: ^0.19.0 
  carousel_slider: ^5.0.0
  grouped_list: ^5.1.2
  rxdart: ^0.27.5
  mask_text_input_formatter: ^2.4.0
  jiffy: ^6.2.1
  shared_preferences: ^2.0.15
  just_the_tooltip: ^0.0.12
  photo_view: ^0.14.0
  google_sign_in: ^6.1.6
  url_launcher: ^6.1.7
  cached_network_image: ^3.2.3
  google_sign_in_web: ^0.12.1
  sentry_flutter: ^7.13.2
  smooth_page_indicator: ^1.0.1
  in_app_update: ^4.0.1
  universal_html: ^2.0.9
  infinite_scroll_pagination: ^4.0.0
  upgrader: ^8.3.0
  sign_in_with_apple: ^5.0.0
  image_network: ^2.5.1
  google_mobile_ads: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  test: ^1.17.12

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app-logo.png"

flutter:
  assets:
    - assets/images/
    - assets/json/
    - assets/icons/
    - assets/icons/google_icon.png
    - assets/icons/googleplay.png
    - assets/icons/shkaf.png

  generate: true
  uses-material-design: true
