// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLUmBkhUcngQXuEuE2218vZdzdpCCTv04',
    appId: '1:656609494072:web:7e5c4ece0a4758109b92cd',
    messagingSenderId: '656609494072',
    projectId: 'moka-2344b',
    authDomain: 'moka-2344b.firebaseapp.com',
    storageBucket: 'moka-2344b.appspot.com',
    measurementId: 'G-NM72CJ2ZH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeUd12lEie5bxBaMaIgpaYsUwKYFZ92w8',
    appId: '1:656609494072:android:4b5fa5100eb430059b92cd',
    messagingSenderId: '656609494072',
    projectId: 'moka-2344b',
    storageBucket: 'moka-2344b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOfBOxfNdBt2_pPSdCwfuQ5y0_fsbeN1s',
    appId: '1:656609494072:ios:376d764e5591eb419b92cd',
    messagingSenderId: '656609494072',
    projectId: 'moka-2344b',
    storageBucket: 'moka-2344b.appspot.com',
    androidClientId: '656609494072-iab5d9juiv6molvq8s3uck024711nvnf.apps.googleusercontent.com',
    iosClientId: '656609494072-psn7m471853rob2if0tidq95mtni2vs2.apps.googleusercontent.com',
    iosBundleId: 'com.aturdiyev.mynotes',
  );

}